### ISSUE TITLE
Get the parameter define in a route

### ISSUE THREAD

**Issue by zaingithub** [skipperbent/simple-php-router#265]
Hi, how can i identify if a route with any name has a or multiple parameter?

ex : 

SimpleRouter::get('/{query}.html', "SimpleController@search")
				->where([ 'query' 	=> '[A-Za-z0-9\-]+' ])
				->name('search');

so i can create (example) : 

SimpleRouter::getParams( 'search' );

it will return 

return array('query');

if the route dosn't has any parameter, it will return "null", etc.

thanks :)

**Comment by skipperbent** [comment]
If you want to know which parameters that has been defined on a route, you should name your route and use the `url` helper function to find the specific route that you are looking for.

There's two ways of doing this. If you are doing this from a controller or callback you can use the `getLoadedRoute` to get the currently loaded route.

**Example:**

```php
request()->getLoadedRoute()->getParameters()
```

Otherwise I would recommend that you name your routes and use the `Router->findRoute($name)` method to get the route you are looking for.

**Example:**

```php
Router::get('/contact', 'PageController@contact')->name('page.contact');

// Finding the route
SimpleRouter::router()->findRoute('page.contact')->getParameters();
```

According to the phpDocs the `findRoute` method will "Find route by alias, class, callback or method.", so if you are unable to name your routes (if they are loaded dynamically etc) you can provide the callback etc. as parameter.

**Comment by jatubio** [comment]
@zaingithub, thank you for ask this.

Just today i have to get de parameters of current router and thank to you i have got the response very fast :)

**Comment by skipperbent** [comment]
Great! I'm glad you got it working and no problem 👍 

I'm closing this issue, if you have any further questions etc. feel free to reopen or create a new issue. 

/ Simon
