### ISSUE TITLE
Optional parameters default value

### ISSUE THREAD

**Issue by Steph-24** [skipperbent/simple-php-router#347]
I tried this code from the documentation :
`SimpleRouter::get('/user/{name?}', function ($name = 'Simon') {
	return $name;
});`

But it seems that the default value doesn't work. The returned value will be null or empty in my case, if my url is "/user/" without a parameter.

I also tried the same thing by using a controller but the result is the same.

**Comment by skipperbent** [comment]
Hi @Steph-24.

Thanks for taking the time to report this issue. You're right - the default parameter value is overwritten, which is not the intended behavior.

The issue has been fixed in the latest release (version 3.4.10.0), along with new unit-tests to ensure that no similar issues will happen in the future.

/ Simon

**Comment by Steph-24** [comment]
Perfect ! Thanks for your help and your time. It works great now.

**Comment by skipperbent** [comment]
No problem, happy to help. Feel free to create another issue if you have any further issues or questions :)

/ Simon
