### ISSUE TITLE
Get Input Text with Form Method POST

### ISSUE THREAD

**Issue by rachmawatiafrida** [skipperbent/simple-php-router#354]
Do you have example how to create search box and redirect to

Router::get('/search/{string}', 'Controller@search'

Thanks,

**Comment by skipperbent** [comment]
@rachmawatiafrida 

Hi @rachmawatiafrida.

You should avoid using a query as a parameter on the url, as certain characters might not be compatible in all browser. 

However it's definitely possible, however you have to use javascript to make the form append the search-term to the url instead of a querystring:

```php
<form method="get" onSubmit="return submit();">
    <input type="text" name="query" id="query">
    <input type="submit" value="Search">
</form>

<script>
function submit()
{
    var url="<?= url('search'); ?>" + document.getElementById('query').value;
    location.href=url;
    return false;
}
</script>
```

Then give your route a name, so we easily can get the url by calling `url()`, like this:

```php
Router::get('/search/{query}', 'Controller@search')->name('search');
```

And extend the regular-expression for the `{string}` parameter to support all characters.

```php
Router::get('/search/{query}', 'Controller@search', ['where' => ['query' => '.+']])->name('search');
```

More info here:
https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

Hope it helps.

/ Simon

**Comment by rachmawatiafrida** [comment]
Why didn't use 
`response()->redirect(url('name'));`
and detect input form method post using `(Request $request)` ?

**Comment by skipperbent** [comment]
@rachmawatiafrida you asked me how to create a search box.

You can get input values by using:

```php
$query = input('query');
```

I'm not sure I understand your question, sorry...

**Comment by rachmawatiafrida** [comment]
Can you check and correct this code?

> in html

```
      <form method="post" action="<?= url('post'); ?>" id="searchform" class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="search-query search form-control" required="required" id="query" autocomplete="off" title="" name="search" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-danger"> <span class="glyphicon glyphicon-search"></span> </button>
      </form>
```

> in routes/web.php

`Router::post('/', 'Controller@postsearch')->setName('post');`
`Router::get('/search/{query}.html', 'Controller@find')->setName('search');`

> in Controller

```
public function postsearch(Request $request){
    	response()->redirect(url('search', ['query' => $request->input('search')]));
}
public function find($query){
    	echo 'This is search page: ' . $query;
}
```
Thanks,

**Comment by skipperbent** [comment]
@rachmawatiafrida 

You need to define a custom regex for the query parameter. Otherwise the route will fail as parameters only matches a-z and 0-9 as default.
```php
Router::get('/search/{query}.html', 'Controller@find', ['where' => ['query' => '.+']])->name('search');
```

The `Request` is not passed automatically. You can call it by using `request()` - but since you want to get input value, you should use the `input` helper function instead.

```php
public function postsearch() {
    	redirect(url('search', ['query' => input('search')]));
}
```

**More info:**

- Parameter regex:
https://github.com/skipperbent/simple-php-router#custom-regex-for-matching-parameters

- Parsing input and parameters:
https://github.com/skipperbent/simple-php-router#input--parameters

/ Simon

**Comment by rachmawatiafrida** [comment]
Finally successfull with `input()->get('query')` .
But URL returned /search/test.html/

How to remove the last slash after .html?

**Comment by skipperbent** [comment]
Great, that's nice to hear! 🙂

In your helpers.php - in the url function you can just trim the ending slash manually. 

```php
function url($name = null, $parameters = null, $getParams = null)
{
    return rtrim(Router::getUrl($name, $parameters, $getParams), '/');
}
```

**Comment by rachmawatiafrida** [comment]
Thank you so much, very like this router.

**Comment by skipperbent** [comment]
Thanks! I'm happy that you find it useful -and thank you for using it.

Feel free to create another issue if you have any further questions, comments, ideas etc.

/ Simon
