### ISSUE TITLE
Question about Router::resource

### ISSUE THREAD

**Issue by vystepanenko** [skipperbent/simple-php-router#355]
hello!
I have controller like
```
class Test
{
    public function testIndex(){}
    public function testShow(){}
}
```
I want to make resource on this class with custom $methodNames. Something like this
```
Router::resource('/test', Test::class)
            ->setMethodNames([
                'testIndex'=>'testIndex',
                'testshow'=>'testshow',
            ]);
```
But when I hit http://mydomain/test/testIndex I received error
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

What I'm doing wrong?

**Comment by skipperbent** [comment]
@vystepanenko 

Not sure about the json syntax-error you are receiving, sounds like it has the `Content-type: application/json` header which fails due to an exception etc.

I think you need to do something like this:

```php
Router::resource('/test', Test::class)
            ->setMethodNames([
                'index'=>'testIndex',
                'show'=>'testshow',
            ]);
```

The default values are defined in the `$methodNames` property in the `Pecee\SimpleRouter\Route\RouteResource` class.

Copy pasta:

```php
protected $methodNames = [
        'index'   => 'index',
        'create'  => 'create',
        'store'   => 'store',
        'show'    => 'show',
        'edit'    => 'edit',
        'update'  => 'update',
        'destroy' => 'destroy',
    ];
```

Otherwise you can implement the `IResourceController` interface and use the default method-names.

/ Simon

**Comment by skipperbent** [comment]
I'm closing this issue due as there has been no response in a while.

Feel free to reopen or create another issue if you have any further questions or issues.

/ Simon
