### ISSUE TITLE
What if two routes matches ? Which one has the priority ?

### ISSUE THREAD

**Issue by Blair2004** [skipperbent/simple-php-router#405]
Hi again, 
i'm facing some situation where in some cases two routes matches. My Concern is there should be a way for a route to have a priority. For example : 
`http://example.com/go`
`http://example.com/go/somewhere`

is matched by the following

```php
<?php
Route::get( '/go', function(){
});
Route::match([ 'get', 'post' ], '/go/{param?}', function(){
// this will match in all case even if it's added before 'Route::get...'
});
```
in my situation, the route with match method alway respond in both cases "/go" and "/go/somewhere". There should be a way to prevent it by taking in consideration the first match for example.

Regards.

**Comment by Blair2004** [comment]
Hi, i've noticed that the priority is set when a controller return a content.

**Comment by skipperbent** [comment]
Hi.

As far as I remember the router should match routes in the order they're added.

I'm not sure if the documentation has been updated on this subject, but in the newer versions of the router, it's possible to render multiple routes. 

In your case both of your routes should match for GET - however it depends on your callbacks. 

If you want the router to stop when a route is matched, you simply return a value in your callback or stop the execution manually (using `response()->json()` etc.). 

Any returned objects that implements the `__toString()` magic method will also prevent other routes from being rendered. 

Perhabs the router should have an option to force continue regardless of the callback output.

Let me know if above explanations helps you resolve your issue, otherwise you could manually edit the order of the routes by adding an event. Otherwise let me know.  

/ Simon

**Comment by Blair2004** [comment]
Yes, that exactly what i've realized.
