### ISSUE TITLE
Parse error in PHP-DI with DELETE route

### ISSUE THREAD

**Issue by scottfriebel** [skipperbent/simple-php-router#425]
I'm getting the following errors when making a request that is routed but only with the DELETE request method. Using the exact same url for a GET/POST request, it runs without a problem. I'm using php v. 7.1.19, php-router v. 4.2.0.4, and php-di v. 6.0.3.
The url that I'm getting the error with is `/api/v1/users/me/projects/8399421535/pages/0/photos/1372` and the route is `api/v1/users/{userid}/projects/{projectid}/photos/{photoid}`

'<b>Warning</b>:  Unsupported declare 'strict_types' in <b>C:\inetpub\wwwroot\DevCreatePhotoCalendars\Studio\classes\vendor\php-di\php-di\src\functions.php</b> on line <b>3</b><br />
<b>Parse error</b>:  syntax error, unexpected ':', expecting '{' in <b>C:\inetpub\wwwroot\DevCreatePhotoCalendars\Studio\classes\vendor\php-di\php-di\src\functions.php</b> on line <b>22</b>'

**Comment by skipperbent** [comment]
You should move this issue to the php-di GitHub page here:
https://github.com/PHP-DI/PHP-DI

It looks like the `declare` function is not supported in PHP in your environment which is called within the `php-di` library. If you are receiving the error when running unit-tests etc. make sure that the php version in CLI is 7.0 or higher.

Also the parse error could be due to your PHP installation not parsing strict types (methods with strictly declared type as parameters) properly resulting in an invalid php-file.

Hope it helps.

/ Simon

**Comment by scottfriebel** [comment]
This issue was moved to PHP-DI/PHP-DI#620

**Comment by scottfriebel** [comment]
@skipperbent Thanks for your response. I did post it in the php-di repo and their response was just a quote of your with an issue with the php version. 
It does appear that php 7 isn't being used. I have no idea why it wouldn't be though. I am loading the request from a live web page on a server, not unit tests or any local execution. 

Also, like I said, the request loads without a problem with the exact same url but as a POST request. It only returns those errors as a DELETE request. What would be different about a DELETE request that would cause those kinds of errors?

**Comment by scottfriebel** [comment]
Ah hah. Just for future reference if anyone else finds this.. My issue was actually in the web.config file. The php 7 handler wasn't set up to accept the DELETE verb so it was being automatically rerouted to the old php 5.6 handler that was. 

Thanks again for your feedback!

**Comment by skipperbent** [comment]
Hi @scottfriebel.

No problem - I'm happy to hear that you solved your issue 😄 

/ Simon
