### ISSUE TITLE
Question about rewriting url to another route

### ISSUE THREAD

**Issue by jatubio** [skipperbent/simple-php-router#448]
Hello, 

I'm rewriting one url to another url's route on boot() method of RouterBootManager. But, when I want to get the url of new route using findRoute('newRouteKey'). But I get nothing because  because 'processRoutes' run after boot() and routes are not loaded and the first line of findRoute() method ($max = count($this->processedRoutes) - 1;) returns 0.

¿They are best place to rewrite one urls where I can use findRoute()?

I'm using 3.4.3 version.

Thanks in advance

**Comment by skipperbent** [comment]
Hi.

I can't remember the behavior for version 3 - you should consider upgrading, it's not a huge hazzle and it would provide you much better support.

You can trigger loading of the routes manually without rendering them by calling the processRoutes method on the Router within your BootManager - not sure if this is a version 4 feature though.

If this doesn't work, like if the router keeps loading in an endless loop, it might be because it tries to reload the BootManager also.

If the BootManager doesn't work in your case, you could try to add a custom event instead before the routes are rendered - this might also be a v4 feature only, not sure...

Let me know what you find and I'll see what I can do when I get to a PC.

/ Simon

**Comment by jatubio** [comment]
Hi, 

Thanks for your response. I'm updating my code to v4 and will try to do this:

> You can trigger loading of the routes manually without rendering them by calling the processRoutes method on the Router within your BootManager - not sure if this is a version 4 feature though.

I will tell you how it was.

**Comment by jatubio** [comment]
I have tried your solution and it has worked.

Since in your original implementation the call to `processRoutes` is done after the `boot`, I assume it is for some reason. 

And, therefore, instead of always forcing a call to `processRoutes` from the `boot`, I have created a custom `Router` class that inherits from yours and I have overwritten the `findRoute()` method to check if the routes have been processed before to find for a route.

I include the code in case you consider it appropriate to add that modification in your implementation:

    public function findRoute(string $name): ?\Pecee\SimpleRouter\Route\ILoadableRoute
    {
        // Si se intenta buscar una ruta y no se han cargado,
        // leemos antes las rutas
        if(count($this->getProcessedRoutes())==0)
        {
            $this->processRoutes($this->routes);
        }

        return parent::findRoute($name);
    }

Again, thank you very much for your help.
Good weekend!

**Comment by skipperbent** [comment]
Hi jatubio.

I'm glad you got it working!

I think the reason for the placement of the bootmanager is due to legacy. In version 3 route-rendering was done in `processRoutes`, but in this version it's done separately, so I've moved the bootmanager below as you suggested.

The fix will be available in the upcoming release version 4.3.

Have a nice weekend!

**Comment by skipperbent** [comment]
This issue has been resolved in version 4.3.0.0.
Feel free to open another issue if you are still experiencing issues.
