### ISSUE TITLE
Add more support for JSON body handling

### ISSUE THREAD

**Issue by b3none** [skipperbent/simple-php-router#460]
Can we add the ability to access data passed via JSON in the body of the request through the regular method as opposed to having to use `input->all()` or `input()->all(['my_field'])`.

**Comment by skipperbent** [comment]
Hi.

Sorry for the late response. I think the reason it doesn't parse the json data (only when using the `all()` method) was to keep performance high and because of the fact that it's hard to determine what type of response the body is (post, get, file etc). Maybe there's a workaround or I'm wrong - but that's the reason behind it only being available in the all method.

Great fix- I'll make sure to add it to the next release.

- Simon
