### ISSUE TITLE
Why not use a psr container instead

### ISSUE THREAD

**Issue by drnkwati** [skipperbent/simple-php-router#477]
Hi
This router is very promising. But I hate the fact that it depends on php-di/php-di.
I think we should be using psr11 container interface or better you can create a container Interface to be implemented by the developer.
Lets leave it simple as in simple-php-router. It should not have many dependencies 
thanks

**Comment by KarelWintersky** [comment]
This repo is dead. 

No error fixes since end of 2018.

**Comment by skipperbent** [comment]
The php-di was a feature request by someone else. I was against it at first, because I wanted people to create their own implementations by overwriting the functionality of the router - but I was convinced and the feature was implemented.

Now we're here and a new hot thing is replacing php-di. Tomorrow it's something else.

I think you're right that the router should be as simple as possible and give the developers the tools to extend and create their own implementations in their projects using whatever technology they prefer.

**Comment by skipperbent** [comment]
Thanks for the nice words by the way. Let me know what you think will be a solution that could satisfy everyone.

/ Simon

**Comment by skipperbent** [comment]
This issue has been resolved in version 4.3.0.0.
Feel free to open another issue if you are still experiencing issues.
