### ISSUE TITLE
Trying to create a pull request

### ISSUE THREAD

**Issue by DeveloperMarius** [skipperbent/simple-php-router#496]
Hello,

I am using git for a while now, but I never created a pull request. I have some changes I wanted to share with/ offer you, but I'm kind of stuck. I cloned the project, switched into the v4-development branch, created a new branch using "git checkout -b name-of-branch", changed the code, commited and now want to push using "git push origin name-of-branch". But I just get a permission error. 
`remote: Permission to skipperbent/simple-php-router.git denied to DeveloperMarius.
fatal: unable to access 'https://github.com/skipperbent/simple-php-router.git/': The requested URL returned error: 403`
After this I just planned to follow the docs here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Can you help me?

Your sincerely,

Marius K.

**Comment by skipperbent** [comment]
Hi Marius.

You can clone the project to your own account, create a new branch there based on the v4-development etc, make your changes and push it to your own new branch.

Then you can go to pull request and create a new one - GitHub will ask you to share the pull request with the original owner (me). If you do this, the pull request will be available on my pull request list and I'll be able to comment and merge the changes to the development branch.

This is done so that changes has to be manually reviewed before they're comitted to the official source :)

Hope it helps, thanks for the contribution and good luck.

- Simon
-------- Originalbesked --------
Til 20. mar. 2021 13.14, DeveloperMarius skrev:

**Comment by DeveloperMarius** [comment]
Hello,

Thank you. I created the pull request.
Looking forward to write with you over there.

~ Marius
