### ISSUE TITLE
TooManyRequestsException

### ISSUE THREAD

**Issue by MichaelKheel** [skipperbent/simple-php-router#571]
Hello, I have a lot of users connecting from one IP and the trotting system constantly blocks all of them. (\Delight\Auth\TooManyRequestsException)

1) Is it possible to whitelist ip for throttling so that the system does not respond to them?
2) Can I change the blocking time?
3) Can I track the time to unlock?

**Comment by skipperbent** [comment]
You can do that pretty easily with a custom middleware.

- 1. Store/merge the users IP along with the time of the request in an array on the `$request` parameter. For example something like:
 ```php
$request->blockList = array_merge((array)$request->blockList, ['ip' => $request->getIp(), 'time' => time()]);
```

- 2. Loop through all IP in your users list and remove all entries where time > your blocking time.

- 3. If users IP is in the list 1 or more times throw your `TooManyRequestsException`. Otherwise do nothing.

- Enjoy

**Comment by MichaelKheel** [comment]
very sorry, I created an issue in the wrong repository. But I am very surprised that we were able to partially answer it, thanks :)

**Comment by skipperbent** [comment]
> very sorry, I created an issue in the wrong repository. But I am very surprised that we were able to partially answer it, thanks :)

That's what happens. Well maybe someone out there can find the answer helpful, who knows. Good luck with your issue and have a nice day!

/ skipperbent
