### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by MarcinOrlowski** [skipperbent/simple-php-router#82]
README says that to install simple-php-router one needs to

    composer require pecee/framework

but that installs whole framework of yours and router. Shouldn't it rather be just router?:

    composer require pecee/simple-router

Also sample code shows

    use \Pecee\SimpleRouter;

but it it will not work, unless changed to

    use \Pecee\SimpleRouter\SimpleRouter;

Also the whole sample is not working because of this line:

    // Do the routing
    SimpleRouter::init($defaultControllerNamespace);

which uses method that does not exist. It should be:

    // Do the routing
    SimpleRouter::start($defaultControllerNamespace);

Next, I tried to figure out how custom exception handler that is mentioned in the README is supposed to work, but I failed to locate any code that would care of the `exceptionHandler` setting key at all. Same for `middleware` key which I am not seeing being handled. Am I missing something?

**Comment by skipperbent** [comment]
Hey, thanks for the feedback - really appreciate it.. i'll fix this right away.

I'm sorry about the documentation. It's has been done on-the-fly and is really not that great, it's been a task of mine to update it and make it nicer, ever since I started the project. 

It does seem like the `ExceptionHandler` feature never really got implemented or somehow got removed. I've fixed this in the next release.

Regarding middleware this should work if you do something like this. The middleware does have to inherit `IMiddleware` class, but should throw an Exception if it doesn't. 

Example:

```php
Router::group(['middleware' => 'BBC\Middleware\SiteDetector'], function() {

    Router::basic('/signup', 'CustomerController@signUp')->setAlias('user.signup');
    Router::basic('/', 'CustomerController@login')->setAlias(['home', 'user.login']);
    Router::basic('/forgot', 'CustomerController@forgot')->setAlias('user.forgot');
    Router::basic('/reset/{token}', 'CustomerController@reset')->setAlias('user.reset');
    Router::get('/signout', 'CustomerController@signOut')->setAlias('user.logout');

    // Dashboard
    Router::group([ 'prefix' => '/dashboard', 'namespace' => '\BBC\Controller\Dashboard', 'exceptionHandler' => '\BBC\Handler\CustomExceptionHandler'], function() {

        Router::get('/', 'DashboardController@home')->setAlias('dashboard.home');
        Router::basic('/new', 'DashboardController@step1')->setAlias('dashboard.book');
        Router::basic('/new/calendar', 'DashboardController@step2')->setAlias('dashboard.book.step2');
        Router::get('/calendar', 'CalendarController@home')->setAlias('dashboard.calendar');
        Router::controller('/service/events/bookable', 'Service\BookableEventsController');
        Router::controller('/service/events', 'Service\EventsController');

    });

});
```

I've added some tests for middleware loading/routes.

**Comment by skipperbent** [comment]
Status so far v 1.7:

- ExceptionHandler feature implemented.
- Documentation updated.

Please reopen another ticket if you still experience issues with the loading Middlewares.

Thanks for the feedback 👍
